// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRD1vawJuFn5ty26Y6LhV9c03Ry_8_Llw',
    appId: '1:866970493619:web:4315201f23c536417f06c6',
    messagingSenderId: '866970493619',
    projectId: 'mon-app-fifa',
    authDomain: 'mon-app-fifa.firebaseapp.com',
    storageBucket: 'mon-app-fifa.firebasestorage.app',
    measurementId: 'G-6P7JFEZP58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEc1RTzLnvpvBKoTyaEgSZ5E8ymqwzaxw',
    appId: '1:866970493619:android:e767258bdd911c447f06c6',
    messagingSenderId: '866970493619',
    projectId: 'mon-app-fifa',
    storageBucket: 'mon-app-fifa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtKXySS8IleSY7TKuOsvcDhnixlAh54k',
    appId: '1:866970493619:ios:f645e627631801177f06c6',
    messagingSenderId: '866970493619',
    projectId: 'mon-app-fifa',
    storageBucket: 'mon-app-fifa.firebasestorage.app',
    iosBundleId: 'com.example.monAppFifa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtKXySS8IleSY7TKuOsvcDhnixlAh54k',
    appId: '1:866970493619:ios:f645e627631801177f06c6',
    messagingSenderId: '866970493619',
    projectId: 'mon-app-fifa',
    storageBucket: 'mon-app-fifa.firebasestorage.app',
    iosBundleId: 'com.example.monAppFifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRD1vawJuFn5ty26Y6LhV9c03Ry_8_Llw',
    appId: '1:866970493619:web:b8330afc2fadc09a7f06c6',
    messagingSenderId: '866970493619',
    projectId: 'mon-app-fifa',
    authDomain: 'mon-app-fifa.firebaseapp.com',
    storageBucket: 'mon-app-fifa.firebasestorage.app',
    measurementId: 'G-KNCR1KTHYY',
  );
}
